name: C++ Build/Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: "Build 🛠️ & Test ⚙️"
    strategy:
      fail-fast: true
      max-parallel: 3
      matrix:
        os: [macos, ubuntu]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v4
    - name: setup-ninja
      uses: wirekang/setup-ninja@v1
      with:
        # suffix from official release(e.g. 'win', 'linux' or 'mac')
        platform: ${{ matrix.os == 'macos' && 'mac' || 'linux' }}
        tag: v1.12.1
    - name: Install latest Clang on MacOS
      if: matrix.os == 'macos'
      run: |
        brew update && brew install llvm
        echo "$(brew --prefix llvm)/bin" >> $GITHUB_PATH
    - name: Build
      run: CLANG=clang++ make all
    - name: Test
      # TODO: add unit tests
      run: echo "--- Test ⚙️" 
